#!/bin/sh

# Check parameters were passed in
if [ -z "$1" ]; then
    echo "Missing studentName parameter"
    exit
fi

STUDENT_NAME=$1

cd students/$STUDENT_NAME

# Change into the first directory in their folder; should be their project
cd *

# Get the remote url
REMOTE=$(git config --get branch.master.remote)
REMOTE_URL=$(git config --get remote.$REMOTE.url)
BASENAME=$(basename "$REMOTE_URL" .git)

# Go back to root of dwa-bash
cd ../../../

# Delete their directory
rm -rf students/$STUDENT_NAME

# Re-run the install script
./install-student-project $STUDENT_NAME $REMOTE_URL
